### ISSUE TITLE
rock deploy isn't restarting service?

### ISSUE THREAD

**Issue by fractallian** [emmerge/rockup#2]
Log message says service restarted after successful deploy but it appears that a `rock restart` is needed to load new code. Result of first restart after a deploy is "true" but subsequent restarts is "false"

**Comment by mccolin** [comment]
This should be solved for ubuntu upstart with `service` subcommand style lifecycle commands (start, stop, restart).

https://github.com/emmerge/rockup/commit/2129e091acc2c3fd689963f7e54bca39c428eedc
